import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFliesBackground from "@/components/FireFliesBackground";
import Sound from "@/components/Sound";
import MagicCursor from "@/components/MagicCursor";


const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Jayant Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground font-inter bodyq")} >

        {children}
        {/* <MagicCursor/> */}
        <FireFliesBackground/>
        <Sound/>
        <div id="my-modal"/>
      </body>
    </html>
  );
}
